### ISSUE TITLE
Docker PostgreSQL driver psycopg2 error on startup

### ISSUE THREAD

**Issue by erikspears** [sidprobstein/swirl-search#69]
This error seems to appear in the Docker Terminal window immediately after the Container comes up:
```
swirl-161f-app-1  | 2022-11-26 13:08:35,922 ERROR    postgresql.py: Error: can't load psycopg2: No module named 'psycopg2', see https://github.com/sidprobstein/swirl-search/wiki/4.-Object-Reference#postgresql
```

Screen grab from a 1.6.1 final Docker install:
![Screenshot 2022-11-26 at 1 16 21 PM](https://user-images.githubusercontent.com/98238295/204105305-b571f6f0-b23d-4ec8-a675-9e354d8c3e3b.png)

Logging the issue because I do have `psycopg2` installed already, yet Docker seems unable to find it, perhaps?  I installed it earlier today as part of a fresh MacOS installation of 1.6.1 final and had the funding DB example working just fine with PostgreSQL; so the driver is there and functioning (or at least, it was).

This results in an error when attempting to query the funding DB example in PostgreSQL from the docs, for example:
`"PostgreSQL_8_4: Error: name 'psycopg2' is not defined",`

**Comment by erikspears** [comment]
Likely related to to Issue #57 , if not the same root cause.

**Comment by sidprobstein** [comment]
Resolved in 1.8

**Comment by sidprobstein** [comment]
This error does not appear in 1.8, however, https://github.com/sidprobstein/swirl-search/issues/88 is an issue now

**Comment by erikspears** [comment]
Quick revisit with the latest 1.8 looks good!

Deleted prior 1.8 images and container from Docker.  Re-pulled and ran `docker compose up` to create fresh container, and the error mentioned above no longer appears.

After muuuch finagling, I made the changes outlined in #88 to get the Postgres Search Provider installed.  However, this error is still returned when searching with that SP active and default:
```
        "[2023-01-16 16:34:50.873219] Error: name 'psycopg2' is not defined",
```

Screen grab from the Results List for the Postgres SP:
![Issue 69 - Results provider details](https://user-images.githubusercontent.com/98238295/212769595-a39811fe-b7f5-48ca-8f80-5e4fe93a1faa.png)

CC:  @sidprobstein , reopening and re-assigning to you for the moment.

**Comment by erikspears** [comment]
Aaaand closing again!  😆  

PEBKAC:  I missed one thing.  I need to run `pip install psycopg2` from within the Docker terminal, and then restart Docker.  Docker of course couldn't care less about my local install of `psycopg2`, it needed its own.  Apologies for all the ticket noise created by my own goofs on this one, folks!

After doing the above, the `psycopg2` error is gone when searching.  I need to sort out the path for Docker to talk to my Postgres, but that's config for me to do, not a bug.
